# Generated by Django 5.1.15 on 2026-04-25 14:13
# Modified to handle partially-applied state from multiple failed prior runs.
#
# Actual DB state before this migration:
#   inventory_branch         — table exists (empty), partial run created it
#   destination_branch_id    — bigint NULL FK, FULLY migrated by prior partial run
#   retailersales.branch_id  — varchar(100) NULL, renamed but type not changed yet

import django.db.models.deletion
from django.db import migrations, models


def clear_retailersales_branch(apps, schema_editor):
    schema_editor.execute(
        "UPDATE inventory_retailersales SET branch_id = NULL"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('inventory', '0004_auditlog'),
    ]

    operations = [
        # inventory_branch already exists — skip CREATE, just update state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Branch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('address', models.CharField(blank=True, max_length=255)),
                    ],
                    options={
                        'verbose_name_plural': 'Branches',
                        'ordering': ['name'],
                    },
                ),
            ],
        ),

        # inventorymovement.destination_branch_id already bigint NULL FK — skip DB, just update state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='inventorymovement',
                    name='destination_branch',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.branch'),
                ),
            ],
        ),

        # retailersales.branch_id is varchar(100) NULL — clear data, then change type + add FK.
        migrations.RunPython(clear_retailersales_branch, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE inventory_retailersales "
                        "MODIFY COLUMN branch_id BIGINT NULL, "
                        "ADD CONSTRAINT inventory_retailersales_branch_fk "
                        "FOREIGN KEY (branch_id) REFERENCES inventory_branch(id) "
                        "ON DELETE SET NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='retailersales',
                    name='branch',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.branch'),
                ),
            ],
        ),
    ]
