# Generated by Django 5.1.15 on 2026-04-25 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_branch_alter_inventorymovement_destination_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retailersales',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='retailersales',
            name='resolution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('returned', 'Returned to Warehouse'), ('written_off', 'Written Off'), ('corrected', 'Corrected Entry')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='retailersales',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailersales',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
