# Generated by Django 5.1.15 on 2026-05-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_retailersales_resolution_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs'), ('bundle', 'bundle'), ('tray', 'tray'), ('bag', 'bag')], default='pcs', max_length=10),
        ),
    ]
