# Generated by Django 5.1.15 on 2026-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="batch_number",
        ),
        migrations.RemoveField(
            model_name="product",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="production_date",
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="production_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
