# Generated by Django 5.1.15 on 2026-05-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_product_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="source_batch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"movement_type": "production_in"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deductions",
                to="inventory.inventorymovement",
            ),
        ),
    ]
