# Generated by Django 5.1.15 on 2026-05-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_inventorymovement_source_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailersales",
            name="delivery_movement",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"movement_type": "delivery_out"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliations",
                to="inventory.inventorymovement",
            ),
        ),
    ]
