# Generated by Django 5.1.15 on 2026-05-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_retailersales_delivery_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="back_order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="closes_back_order",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"movement_type": "back_order"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfillment",
                to="inventory.inventorymovement",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="loss_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warehouse", "Warehouse"),
                    ("transit", "In Transit"),
                    ("branch", "At Branch"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="source_delivery",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"movement_type": "delivery_out"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_movements",
                to="inventory.inventorymovement",
            ),
        ),
    ]
