# Generated by Django 5.1.15 on 2026-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventorymovement_back_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='back_order_status',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='closes_back_order',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='loss_location',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('transit', 'In Transit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('production_in', 'Production In'), ('delivery_out', 'Delivery Out'), ('return_in', 'Return In'), ('loss', 'Stock Loss')], max_length=20),
        ),
    ]
