# Generated by Django 5.1.15 on 2026-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_inventorymovement_back_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, related_name='assigned_sales_reps', to='inventory.branch'),
        ),
    ]
