# Generated by Django 5.1.15 on 2026-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_userprofile_assigned_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('production_in', 'Production In'), ('delivery_out', 'Delivery Out'), ('loss', 'Stock Loss')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retailersales',
            name='resolution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('written_off', 'Written Off'), ('corrected', 'Corrected Entry')], default='pending', max_length=20),
        ),
    ]
